base_url = "https://sssssssuzuki.github.io"
compile_sass = false
build_search_index = false
title = "Suzuki Shun's homepage"
theme = "blow"
default_language = "ja"

taxonomies = [
    {name = "tags", paginate_by = 5, feed = true},
    {name = "categories", paginate_by = 5, feed = true},
]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "base16-ocean-dark"
render_emoji = true

[extra]
enable_search = false
enable_sidebar = true
enable_multilingue = false
enable_adsense = false
enable_toc = true

[extra.navbar]
items = [
    { lang = "ja", links = [
        { url = "/", name = "Home" },
        { url = "/categories", name = "Categories" },
        { url = "/tags", name = "Tags" },
    ] }
]
title = "Suzuki Shun's homepage"

[extra.sidebar]
items = [
    { lang = "ja", links = [
        { url = "/about", name = "About" },
        { url = "/markdown", name = "Markdown" },
        { url = "/blog", name = "Blog" },
    ] }
]

[extra.index]
title = "Suzuki Shun"
image = "https://sssssssuzuki.github.io/logo.svg"

[extra.default_author]
name = "Suzuki Shun"

[extra.social]
github = "https://github.com/sssssssuzuki"
gitlab = ""
twitter = ""
linkedin = ""
email = "suzuki@hapis.k.u-tokyo.ac.jp"

