base_url = "https://sssssssuzuki.github.io"
compile_sass = true
build_search_index = false
title = "Suzuki Shun's homepage"
theme = "blow"
default_language = "ja"

[markdown]
highlight_code = true

highlight_theme = "base16-ocean-dark"

[extra]
enable_search = false
enable_sidebar = true
enable_multilingue = false
enable_adsense = false

[extra.navbar]
items = [
    { lang = "ja", links = [
        { url = "/", name = "Home" },
        { url = "/categories", name = "Categories" },
        { url = "/tags", name = "Tags" },
    ] }
]
title = "Suzuki Shun's homepage"

[extra.sidebar]
items = [
    { lang = "ja", links = [
        { url = "/about", name = "About" },
        { url = "/markdown", name = "Markdown" },
        { url = "/blog", name = "Blog" },
    ] }
]

[extra.index]
title = "Suzuki Shun"
image = "https://raw.githubusercontent.com/sssssssuzuki/sssssssuzuki.github.io/master/content/logo/logo.svg"

[extra.default_author]
name = "Suzuki Shun"

[extra.social]
github = "https://github.com/sssssssuzuki"
gitlab = ""
twitter = ""
linkedin = ""
email = "suzuki@hapis.k.u-tokyo.ac.jp"

