base_url = "https://sssssssuzuki.github.io/homepage/"
compile_sass = true
build_search_index = false
title = "Suzuki Shun's homepage"
theme = "oceanic-zen"

[markdown]
highlight_code = true

[extra]
author = "Suzuki Shun"
github = "sssssssuzuki"
