base_url = "https://s5suzuki.github.io"
compile_sass = false
build_search_index = false
title = "Suzuki Shun's homepage"
theme = "blow"
default_language = "ja"

taxonomies = [
    {name = "tags", paginate_by = 5, feed = true},
    {name = "categories", paginate_by = 5, feed = true},
]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "base16-ocean-dark"
render_emoji = true

[extra]
enable_search = false
enable_sidebar = false
enable_multilingue = false
enable_adsense = false

[extra.navbar]
items = [
    { lang = "ja", links = [
        { url = "/", name = "Home" },
        { url = "/about/about-me", name = "About me"},
        { url = "/posts", name = "Posts"},
        { url = "/categories", name = "Categories" },
        { url = "/tags", name = "Tags" },
      ] }
]
title = "Suzuki Shun's homepage"

[extra.index]
title = "Suzuki Shun"
image = "https://s5suzuki.github.io/logo.svg"

[extra.default_author]
name = "Suzuki Shun"

[extra.social]
github = "https://github.com/s5suzuki"
gitlab = ""
twitter = ""
linkedin = ""
email = "suzuki@hapis.k.u-tokyo.ac.jp"
